namespace TnsTool.Utils {
    static class TnsError {
        private static readonly Dictionary<int, string> errorCodes = new Dictionary<int, string>();

        public static string GetError(int code) {
            return errorCodes[code];
        }
        static TnsError() {
            errorCodes.Add(00000, "Not An Error");
            errorCodes.Add(00001, "INTCTL: error while getting command line from the terminal");
            errorCodes.Add(00002, "INTCTL: error while starting the Interchange");
            errorCodes.Add(00003, "INTCTL: error while sending request to the Interchange");
            errorCodes.Add(00004, "INTCTL: error while starting the Navigator");
            errorCodes.Add(00005, "INTCTL: error while sending request to the Navigator");
            errorCodes.Add(00006, "INTCTL: HOST variable is not defined");
            errorCodes.Add(00007, "INTCTL: unknown host");
            errorCodes.Add(00008, "INTCTL: could not contact destination Navigator");
            errorCodes.Add(00009, "INTCTL: could not contact destination Connection Manager");
            errorCodes.Add(00010, "Error while flushing NS context");
            errorCodes.Add(00011, "INTCTL: error while starting the Connection Manager");
            errorCodes.Add(00012, "INTCTL: error while processing Connection Manager request");
            errorCodes.Add(00013, "INTCTL: error while performing NS disconnect command");
            errorCodes.Add(00014, "INTCTL: error while opening terminal input channel");
            errorCodes.Add(00015, "INTCTL: error while closing terminal input channel");
            errorCodes.Add(00016, "INTCTL: error while performing NS send command");
            errorCodes.Add(00017, "INTCTL: error while performing NS receive command");
            errorCodes.Add(00018, "INTCTL: TNS_ADMIN not defined");
            errorCodes.Add(00019, "INTCTL: error initializing the national language interface");
            errorCodes.Add(00020, "INTCTL: missing NAVIGATOR_DATA in TNSNAV.ORA");
            errorCodes.Add(00021, "INTCTL: missing INTERCHANGE_DATA in INTCHG.ORA");
            errorCodes.Add(00022, "INTCTL: missing CMANAGER_NAME in INTCHG.ORA");
            errorCodes.Add(00023, "INTCTL: missing ADDRESS(es) in config files");
            errorCodes.Add(00024, "INTCTL: Unable to contact Navigator to obtain Connection Manager address");
            errorCodes.Add(00025, "INTCTL: The ORACLE environment is not set up correctly");
            errorCodes.Add(00026, "INTCTL: TNS_ADMIN directory set, and is being used");
            errorCodes.Add(00027, "INTCTL: Could not resolve Navigator's name/address");
            errorCodes.Add(00028, "INTCTL: Could not resolve Connection Manager's name/address");
            errorCodes.Add(00031, "INTCTL: internal NT error");
            errorCodes.Add(00032, "INTCTL: internal NS error");
            errorCodes.Add(00033, "INTCTL: internal NL error");
            errorCodes.Add(00034, "INTCTL: internal NR error");
            errorCodes.Add(00035, "INTCTL: error while constructing full file name");
            errorCodes.Add(00036, "INTCTL: error reading from Navigator or Connection Manager error files");
            errorCodes.Add(00037, "INTCTL: error opening Navigator or Connection Manager error files");
            errorCodes.Add(00038, "INTCTL: Poorly formed address or command string");
            errorCodes.Add(00039, "INTCTL: error while spawning a process");
            errorCodes.Add(00040, "INTCTL: failed to initialize trace context- Continuing anyway");
            errorCodes.Add(00041, "INTCTL: Navigator already running. Start operation cancelled");
            errorCodes.Add(00042, "INTCTL: CMANAGER already running. Start operation cancelled");
            errorCodes.Add(00043, "The CMANAGER has active connections, do you still want to stop it (y/n)?");
            errorCodes.Add(00044, "INTCTL: You must have an INTCHG.ORA file to contact the Connection Manager");
            errorCodes.Add(00045, "INTCTL: Could not contact the Navigator on address");
            errorCodes.Add(00046, "INTCTL: Could not contact the CMANAGER on address");
            errorCodes.Add(00060, "INTCTL: Bad command: only the STATUS command can be used on remote Interchanges");
            errorCodes.Add(00061, "INTCTL: Bad command or syntax error: You must specify a trace level");
            errorCodes.Add(00062, "INTCTL: Bad command or syntax error: For help type help/h/?");
            errorCodes.Add(00063, "INTCTL: Failed to allocate memory for buffers");
            errorCodes.Add(00064, "INTCTL: Failed to find CMANAGER_NAME in INTCHG.ORA");
            errorCodes.Add(00065, "INTCTL: Command cannot be executed remotely");
            errorCodes.Add(00070, "INTCTL usage: [intctl] command &lt;process_name&gt; [argument]");
            errorCodes.Add(00071, "where command is one of following: ");
            errorCodes.Add(00072, "* start - start up process_name");
            errorCodes.Add(00073, "* stop/abort - stop the process_name");
            errorCodes.Add(00074, "* status - get statistics from the process_name");
            errorCodes.Add(00075, "NOTE: the user may get the status info of a remote");
            errorCodes.Add(00076, "component by specifying the component name in");
            errorCodes.Add(00077, "the argument field");
            errorCodes.Add(00078, "* log_on - ask process_name to turn logging on");
            errorCodes.Add(00079, "* log_off - ask process_name to turn logging off");
            errorCodes.Add(00080, "* force_log - ask process_name to dump its state");
            errorCodes.Add(00081, "* trace_on - ask process name to turn tracing on");
            errorCodes.Add(00082, "NOTE: the user MUST specify a trace level");
            errorCodes.Add(00083, "(USER or ADMIN) in the argument field");
            errorCodes.Add(00084, "* trace_off - ask process name to turn tracing off");
            errorCodes.Add(00085, "* reread - ask the process name to reread parameter files");
            errorCodes.Add(00086, "* reload - ask the Navigator to reload TNSNET.ORA");
            errorCodes.Add(00087, "* version - ask the process name to display its version number");
            errorCodes.Add(00088, "* exit - quit the Interchange controller");
            errorCodes.Add(00089, "process_name is one of Interchange, CMANAGER, or Navigator");
            errorCodes.Add(00090, "* Interchange - will ask the Interchange");
            errorCodes.Add(00091, "* Navigator (or navgatr) - will ask the Navigator only");
            errorCodes.Add(00092, "* CMANAGER (or intlsnr) - will ask the Cmanager only");
            errorCodes.Add(00093, "argument is only supplied to either status or trace_on");
            errorCodes.Add(00094, "* to status - argument is considered the remote process_name");
            errorCodes.Add(00095, "* to trace_on - argument is considered the trace level");
            errorCodes.Add(00100, "Unable to allocate memory");
            errorCodes.Add(00101, "File operation error");
            errorCodes.Add(00102, "Keyword-Value binding operation error");
            errorCodes.Add(00103, "Parameter file load error");
            errorCodes.Add(00104, "Data stream open/access error");
            errorCodes.Add(00105, "Could not initialize tracing");
            errorCodes.Add(00106, "Failed to open log file");
            errorCodes.Add(00107, "Unable to initialize TNS global data");
            errorCodes.Add(00108, "TNS_ADMIN not defined");
            errorCodes.Add(00109, "Message could not be printed; not enough memory");
            errorCodes.Add(00110, "Could not initialize network from file TNSNET.ORA");
            errorCodes.Add(00111, "Failed to get configuration data from file");
            errorCodes.Add(00112, "Failed to find configuration file name");
            errorCodes.Add(00113, "Failed to open error log file");
            errorCodes.Add(00114, "Internal error- Allocation of addresses not performed");
            errorCodes.Add(00115, "Could not allocate pump global buffers");
            errorCodes.Add(00116, "Pump failed during initial bequeath");
            errorCodes.Add(00117, "Internal error- No data passed through pump");
            errorCodes.Add(00119, "Missing PUMP_CONNECTIONS in INTCHG.ORA");
            errorCodes.Add(00120, "Missing PUMPS in INTCHG.ORA");
            errorCodes.Add(00121, "Missing CMANAGER_NAME in INTCHG.ORA");
            errorCodes.Add(00122, "Missing ADDRESS(es) in TNSNET.ORA file");
            errorCodes.Add(00123, "Unable to perform a listen on configured ADDRESS(es)");
            errorCodes.Add(00124, "Internal error - Unable to create empty address");
            errorCodes.Add(00125, "Failed to get number of Interchanges in TNSNET.ORA");
            errorCodes.Add(00126, "Missing Connection Manager name and address in TNSNET.ORA");
            errorCodes.Add(00127, "Missing Connection Manager name in TNSNET.ORA");
            errorCodes.Add(00128, "Missing COMMUNITY in TNSNET.ORA");
            errorCodes.Add(00129, "Internal error - Failed to create new community");
            errorCodes.Add(00130, "Failed to create Interchange's internal address");
            errorCodes.Add(00131, "Missing COMMUNITY in COMMUNITY_COST_LIST in TNSNET.ORA");
            errorCodes.Add(00132, "COST value must be an integer greater than 0");
            errorCodes.Add(00133, "Missing LOCAL_COMMUNITIES field in TNSNAV.ORA");
            errorCodes.Add(00134, "Missing COMMUNITY component in addresses for the Navigator in TNSNAV.ORA");
            errorCodes.Add(00135, "Missing TNS error message file");
            errorCodes.Add(00136, "Did not register product/facility for TNS error message");
            errorCodes.Add(00137, "Failed to get TNS error message file entry");
            errorCodes.Add(00138, "Failed to find ORACLE executable directory");
            errorCodes.Add(00139, "Internal - Data passed from the Interchange listener is poorly formed");
            errorCodes.Add(00140, "Interchange specified was not found in network tables");
            errorCodes.Add(00141, "Failed to get file stream information");
            errorCodes.Add(00142, "Community mismatch in TNSNAV.ORA");
            errorCodes.Add(00143, "Illegal PREFERRED_CMANAGERS entry in TNSNAV.ORA");
            errorCodes.Add(00144, "PUMP_CONNECTIONS value in INTCHG.ORA is too large.");
            errorCodes.Add(00145, "PUMPS value in INTCHG.ORA is too large.");
            errorCodes.Add(00146, "Internal-- Retry data request withing pump.");
            errorCodes.Add(00147, "Failed to start a pre-spawned pump.");
            errorCodes.Add(00200, "Unable to do nsanswer on contextresult=string");
            errorCodes.Add(00201, "Unable to read answer connection data :string:");
            errorCodes.Add(00202, "Failure in redirecting call : Original to string Redirect to string");
            errorCodes.Add(00203, "Unable to start tracing in intlsnr");
            errorCodes.Add(00204, "Started tracing in intlsnr");
            errorCodes.Add(00205, "Turning off tracing in intlsnr");
            errorCodes.Add(00206, "Status Information for Interchange string:");
            errorCodes.Add(00207, "Uptime : number days number hr. number min. number sec");
            errorCodes.Add(00208, "Logging :");
            errorCodes.Add(00209, "Tracing :");
            errorCodes.Add(00210, "Total Pumps Available : number");
            errorCodes.Add(00211, "Total Active Pumps : number");
            errorCodes.Add(00212, "Total Pumps Started : number");
            errorCodes.Add(00213, "Available Connections : number");
            errorCodes.Add(00214, "Total Connections in Use : number");
            errorCodes.Add(00215, "Total Successful Connections : number");
            errorCodes.Add(00216, "Total Failed Connections : number");
            errorCodes.Add(00217, "Total Bytes of Data : number");
            errorCodes.Add(00218, "Current Bytes/Sec. : number");
            errorCodes.Add(00219, "Pump Strategy :");
            errorCodes.Add(00220, "Pump Breakdown--------------");
            errorCodes.Add(00221, "Pump Connections Total Data Bytes/Second");
            errorCodes.Add(00222, "-------------------------------------------------------------------");
            errorCodes.Add(00223, "numbernumbernumbernumber");
            errorCodes.Add(00224, "No more connections available");
            errorCodes.Add(00225, "Unable to bequeath connection to pump");
            errorCodes.Add(00226, "Unable to contact pump number to send broadcast message string");
            errorCodes.Add(00227, "Unable to contact pump; Connection Manager declared pump dead");
            errorCodes.Add(00228, "Failure in finding pump data");
            errorCodes.Add(00229, "Error in call: unable to deliver message:string:stringstringstring");
            errorCodes.Add(00230, "Cannot start new pump process:stringstringProtocol Adapter errors:number");
            errorCodes.Add(00231, "Pump is alive");
            errorCodes.Add(00232, "Unable to setup connection");
            errorCodes.Add(00233, "Interchange failed to make contact with destination with errors:stringstringstring");
            errorCodes.Add(00234, "Connect data for failed call:CALL DATA =stringRECEIVE DATA = :string:");
            errorCodes.Add(00235, "Aborting connection:Protocol Apapter errors:string;number,numberstring;number,number");
            errorCodes.Add(00236, "Failed to initialize tracing");
            errorCodes.Add(00237, "Failed to refuse connection");
            errorCodes.Add(00238, "Pump number @: string:");
            errorCodes.Add(00239, "Connection Manager has been stopped");
            errorCodes.Add(00240, "Connection Manager: Logging is now ON");
            errorCodes.Add(00241, "Connection Manager: Logging is now OFF");
            errorCodes.Add(00242, "Connection Manager: Tracing is now ON");
            errorCodes.Add(00243, "Connection Manager: Tracing is now OFF");
            errorCodes.Add(00244, "Connection Manager: Request Failed");
            errorCodes.Add(00245, "Connection Manager: Failed to open log file");
            errorCodes.Add(00246, "Connection Manager: Failed to start tracing");
            errorCodes.Add(00247, "Unable to allocate memory for configuration data from TNSNET.ORA file");
            errorCodes.Add(00248, "Unable to get information from file :string:Exiting with NR error:number");
            errorCodes.Add(00249, "Unable to read network configuration data from file string with error:");
            errorCodes.Add(00250, "Navigator has been started");
            errorCodes.Add(00251, "Failure in nstest: ");
            errorCodes.Add(00252, "Unable to handle route request:string");
            errorCodes.Add(00253, "Error in reading network configuration data from file string with errorstring");
            errorCodes.Add(00254, "Navigator has been stopped");
            errorCodes.Add(00255, "Closing down log, stopping Navigator");
            errorCodes.Add(00256, "Status of Navigator:");
            errorCodes.Add(00257, "Number of Successful Requests : number");
            errorCodes.Add(00258, "Number of Failed Requests : number");
            errorCodes.Add(00259, "Disabled Interchange list:");
            errorCodes.Add(00260, "-------------------------------------------------------------------");
            errorCodes.Add(00261, "Interchange Name Community Link Down Time Remaining (secs) ");
            errorCodes.Add(00262, "stringstringnumber");
            errorCodes.Add(00263, "Navigator: Request Failed");
            errorCodes.Add(00264, "Navigator: Failed to reload configuration data");
            errorCodes.Add(00265, "Navigator: Reloaded network configuration data");
            errorCodes.Add(00266, "Navigator: Unknown Request");
            errorCodes.Add(00267, "Navigator: Internal Error");
            errorCodes.Add(00268, "ON");
            errorCodes.Add(00269, "OFF");
            errorCodes.Add(00270, "string: Terminal Errorstring");
            errorCodes.Add(00271, "Connection Manager");
            errorCodes.Add(00272, "Navigator");
            errorCodes.Add(00273, "Navigator: Logging is now ON");
            errorCodes.Add(00274, "Navigator: Logging is now OFF");
            errorCodes.Add(00275, "Navigator: Tracing is now ON");
            errorCodes.Add(00276, "Navigator: Tracing is now OFF");
            errorCodes.Add(00277, "Navigator: Request Failed");
            errorCodes.Add(00278, "Navigator: Failed to Open Log file");
            errorCodes.Add(00279, "Navigator: Failed to Start Tracing");
            errorCodes.Add(00280, "Max Avg Bytes/Sec : number");
            errorCodes.Add(00281, "Connection Manager: Forced Log output");
            errorCodes.Add(00282, "Connection Manager: Failed to force log, logging is off");
            errorCodes.Add(00283, "Listening on the following TNS addresses:");
            errorCodes.Add(00284, "Imm Max Avg Bytes/Sec : number");
            errorCodes.Add(00285, "Avg Connect Time (secs) : number");
            errorCodes.Add(00286, "Max Connect Time (secs) : number");
            errorCodes.Add(00287, "Min Connect Time (secs) : number");
            errorCodes.Add(00288, "Navigator: Failed to Disable Interchange");
            errorCodes.Add(00289, "Navigator: Disabled Interchange");
            errorCodes.Add(00290, "Navigator: Failed to Enable Interchange");
            errorCodes.Add(00291, "Navigator: Enabled Interchange");
            errorCodes.Add(00292, "Log File Name :string");
            errorCodes.Add(00293, "Trace File Name :string");
            errorCodes.Add(00294, "Connection Manager: Security is enabled, you cannot STOP the Interchange");
            errorCodes.Add(00295, "Navigator: Security is enabled, you cannot STOP the Navigator");
            errorCodes.Add(00296, "Stoppable :");
            errorCodes.Add(00297, "Logging Level :");
            errorCodes.Add(00298, "Request to Navigator:string");
            errorCodes.Add(00299, "Response from Navigator:string");
            errorCodes.Add(00300, "***Disabling Interchange :");
            errorCodes.Add(00301, "***Enabling Interchange :");
            errorCodes.Add(00302, "Connection Manager: Unknown Request");
            errorCodes.Add(00303, "Connection Manager: Reread parameter data");
            errorCodes.Add(00304, "Status Information for Connection Manager:");
            errorCodes.Add(00305, "The Navigator encountered an invalid/unknown trace level");
            errorCodes.Add(00306, "Connection Manager encountered an invalid/unknown trace level");
            errorCodes.Add(00307, "Navigator: Reread parameter data");
            errorCodes.Add(00308, "Navigator: Failed to open log while rereading parameter data");
            errorCodes.Add(00309, "Connection Manager: Failed to open log while re-reading parameter data");
            errorCodes.Add(00310, "Navigator: Failed to start tracing after rereading parameter data");
            errorCodes.Add(00311, "Connection Manager: Failed to start tracing after rereading parameter data");
            errorCodes.Add(00312, "Connection Manager: Failed to get version information");
            errorCodes.Add(00313, "Navigator: Failed to get version information");
            errorCodes.Add(00314, "Protocol Adapter Errors: number,number");
            errorCodes.Add(00315, "Failed to allocate larger connect data area for getting pump data: number");
            errorCodes.Add(00316, "Ran out of data buffers in the pump");
            errorCodes.Add(00317, "Failed to contact Connection Manager");
            errorCodes.Add(00501, "Cannot allocate memory");
            errorCodes.Add(00502, "Invalid argument");
            errorCodes.Add(00503, "Illegal ADDRESS parameters");
            errorCodes.Add(00504, "Operation not supported");
            errorCodes.Add(00505, "Operation timed out");
            errorCodes.Add(00506, "Operation would block");
            errorCodes.Add(00507, "Connection closed");
            errorCodes.Add(00508, "No such protocol adapter");
            errorCodes.Add(00509, "Buffer overflow");
            errorCodes.Add(00510, "Internal limit restriction exceeded");
            errorCodes.Add(00511, "No listener");
            errorCodes.Add(00512, "Address already in use");
            errorCodes.Add(00513, "Destination host unreachable");
            errorCodes.Add(00514, "Contexts have different wait/test functions");
            errorCodes.Add(00515, "Connect failed because target host or object does not exist");
            errorCodes.Add(00516, "Permission denied");
            errorCodes.Add(00517, "Lost contact");
            errorCodes.Add(00518, "Incomplete read or write");
            errorCodes.Add(00519, "Operating system resource quota exceeded");
            errorCodes.Add(00520, "Syntax error");
            errorCodes.Add(00521, "Missing keyword");
            errorCodes.Add(00522, "Operation was interrupted");
            errorCodes.Add(00523, "Previous operation was busy");
            errorCodes.Add(00524, "Current operation is still in progress");
            errorCodes.Add(00525, "Insufficient privilege for operation");
            errorCodes.Add(00526, "No caller (false async event)");
            errorCodes.Add(00527, "Protocol Adapter not loadable");
            errorCodes.Add(00528, "Protocol Adapter not loaded");
            errorCodes.Add(00530, "Protocol adapter error");
            errorCodes.Add(00532, "No previous async operation to wait on");
            errorCodes.Add(00533, "Connection dissolved or not yet made");
            errorCodes.Add(00534, "Failed to grant connection ownership to child");
            errorCodes.Add(00535, "Failed to send or receive disconnect message");
            errorCodes.Add(00536, "Connection entered inappropriate state");
            errorCodes.Add(00537, "Index into protocol adapter table is out of legal range");
            errorCodes.Add(00539, "Network or Protocol services are down");
            errorCodes.Add(00540, "SSL protocol adapter failure");
            errorCodes.Add(00541, "underlying transport does not exist.");
            errorCodes.Add(00542, "SSL Handshake failed");
            errorCodes.Add(00543, "internal error");
            errorCodes.Add(00544, "unsupported operation");
            errorCodes.Add(00545, "parameter retrieval failure");
            errorCodes.Add(00546, "control failure");
            errorCodes.Add(00547, "user information retrieval failed");
            errorCodes.Add(00548, "value specified for client authentication parameter is not boolean");
            errorCodes.Add(00549, "value specified for the SSL version is not valid");
            errorCodes.Add(00550, "disconnection error");
            errorCodes.Add(00551, "underlying transport connection failed");
            errorCodes.Add(00552, "no valid cipher suites were specified");
            errorCodes.Add(00553, "read failed");
            errorCodes.Add(00554, "write failed");
            errorCodes.Add(00555, "no directory specified for wallet resource locator");
            errorCodes.Add(00556, "no method specified for wallet retrieval");
            errorCodes.Add(00557, "unsupported wallet retrieval method");
            errorCodes.Add(00558, "Entrust login failed");
            errorCodes.Add(00559, "load of Entrust certificate failed");
            errorCodes.Add(00560, "extraction of name from Entrust certificate failed");
            errorCodes.Add(00580, "Read failed due to closed or invalid transport connection");
            errorCodes.Add(00581, "Send failed due to timeout");
            errorCodes.Add(00582, "Receive failed due to timeout");
            errorCodes.Add(00583, "Valid node checking: unable to parse configuration parameters");
            errorCodes.Add(00584, "Valid node checking configuration error");
            errorCodes.Add(01000, "spawn [&lt;listener_name&gt;] &lt;spawn_alias&gt; [&lt;(ARGUMENTS='arg0, arg1,...')&gt;]");
            errorCodes.Add(01001, "start [&lt;listener_name&gt;] : start listener");
            errorCodes.Add(01002, "stop [&lt;listener_name&gt;] : stop listener");
            errorCodes.Add(01003, "status [&lt;listener_name&gt;] : get the status of listener");
            errorCodes.Add(01004, "reload [&lt;listener_name&gt;] : reload the parameter files and SIDs");
            errorCodes.Add(01005, "trace OFF | USER | ADMIN | SUPPORT [&lt;listener_name&gt;] : set tracing to the specified level");
            errorCodes.Add(01006, "set password : set the password for subsequent calls");
            errorCodes.Add(01007, "quit | exit : exit LSNRCTL");
            errorCodes.Add(01008, "version [&lt;listener_name&gt;] : get the version information of the listener");
            errorCodes.Add(01009, "service [&lt;listener_name&gt;] : get the service information of the listener");
            errorCodes.Add(01013, "set|show trc_{ } [value]: set|show trace parameters of current listener");
            errorCodes.Add(01014, "set|show log_{ } [value]: set|show log parameters of current listener");
            errorCodes.Add(01015, "set|show parm_name [value]: sets|shows current listener parm values");
            errorCodes.Add(01016, "change_password [&lt;listener_name&gt;]: changes the password of the listener");
            errorCodes.Add(01017, "set|show current_listener [&lt;listener_name&gt;]: sets|shows current listener");
            errorCodes.Add(01018, "save_config [&lt;listener_name&gt;]: saves configuration changes to parameter file");
            errorCodes.Add(01019, "set rawmode ON | OFF: set output mode for services and status commands");
            errorCodes.Add(01020, "STATUS of the LISTENER");
            errorCodes.Add(01021, "------------------------");
            errorCodes.Add(01022, "Alias string");
            errorCodes.Add(01023, "Version string");
            errorCodes.Add(01024, "Trace Level string");
            errorCodes.Add(01025, "Security string");
            errorCodes.Add(01026, "Start Date string");
            errorCodes.Add(01027, "Listener Trace File string");
            errorCodes.Add(01028, "Listener Log File string");
            errorCodes.Add(01029, "Services Summary...");
            errorCodes.Add(01030, "The listener supports no services");
            errorCodes.Add(01033, "Listener Parameter File string");
            errorCodes.Add(01034, "Uptime number days number hr. number min. number sec");
            errorCodes.Add(01038, "string established:string refused:string current:string max:string state:string");
            errorCodes.Add(01039, "stringhas string service handler(s)");
            errorCodes.Add(01040, "SNMP string");
            errorCodes.Add(01042, "Current Listener is string");
            errorCodes.Add(01043, "Password changed for string");
            errorCodes.Add(01044, "string(Registered)has string service handler(s)");
            errorCodes.Add(01045, "string(Not Registered)has string service handler(s)");
            errorCodes.Add(01046, "Saved string configuration parameters.");
            errorCodes.Add(01047, "Old Parameter File string");
            errorCodes.Add(01048, "No changes to save for string.");
            errorCodes.Add(01049, "string (string)has string service handler(s)");
            errorCodes.Add(01050, "string");
            errorCodes.Add(01052, "The command completed successfully");
            errorCodes.Add(01053, "Connecting to string");
            errorCodes.Add(01054, "Contacted the listener successfully");
            errorCodes.Add(01055, "Successfully stopped the listener");
            errorCodes.Add(01057, "Program name:");
            errorCodes.Add(01058, "Arguments :");
            errorCodes.Add(01059, "Environment :");
            errorCodes.Add(01060, "The password has has been set to:");
            errorCodes.Add(01061, "The password has not been set");
            errorCodes.Add(01062, "The db subagent is already running.");
            errorCodes.Add(01063, "The db subagent is not started.");
            errorCodes.Add(01064, "Listener configuration changes will not be persistent");
            errorCodes.Add(01065, "Raw mode is string");
            errorCodes.Add(01066, "Presentation:");
            errorCodes.Add(01067, "Service display mode is string");
            errorCodes.Add(01070, "Starting string: please wait...");
            errorCodes.Add(01071, "string is set to string");
            errorCodes.Add(01072, "Started at string");
            errorCodes.Add(01073, "Listening on:");
            errorCodes.Add(01074, "Error listening on:");
            errorCodes.Add(01075, "Opened log file:");
            errorCodes.Add(01076, "Opened trace file:");
            errorCodes.Add(01077, "Opened parameter file:");
            errorCodes.Add(01078, "Opened name lookup file:");
            errorCodes.Add(01079, "Attempted to bequeath:");
            errorCodes.Add(01080, "Listener failed to start. See the error message(s) above...");
            errorCodes.Add(01081, "Started with pid=string");
            errorCodes.Add(01082, "Running in PROXY mode");
            errorCodes.Add(01083, "Running in GSM mode");
            errorCodes.Add(01090, "No longer listening on:");
            errorCodes.Add(01091, "Listener(VNCR option number) rejected Registration request from destination string");
            errorCodes.Add(01093, "string * string * number");
            errorCodes.Add(01094, "string * number");
            errorCodes.Add(01095, "string * string * string * number");
            errorCodes.Add(01096, "string * string * string * string * string * number");
            errorCodes.Add(01097, "TIMESTAMP * CONNECT DATA [* PROTOCOL INFO] * EVENT [* SID] * RETURN CODE");
            errorCodes.Add(01098, "TIMESTAMP * CONNECT DATA * ADDRESS * [PRESENTATION *] COMMAND * ERRORTIMESTAMP * [INSTANCE NAME *] [ADDRESS *] [PRESENTATION *] COMMAND * ERROR-------------------------------------------------------------------------------");
            errorCodes.Add(01099, "string * string * string * string * number");
            errorCodes.Add(01100, "TNS returned error number when attempting to start the listener");
            errorCodes.Add(01101, "Could not find listener name or service name string");
            errorCodes.Add(01102, "TNS application contacted was not the listener");
            errorCodes.Add(01103, "Protocol specific component of the address is incorrectly specified");
            errorCodes.Add(01106, "Listener using listener name string has already been started");
            errorCodes.Add(01107, "A valid trace level was not specified");
            errorCodes.Add(01108, "Listener password prompt failed");
            errorCodes.Add(01109, "Listener password encryption failed");
            errorCodes.Add(01110, "Mismatch - password unchanged");
            errorCodes.Add(01111, "Log status can either be ON or OFF");
            errorCodes.Add(01112, "Plug and play can either be ON or OFF");
            errorCodes.Add(01113, "save_config_on_stop can either be ON or OFF");
            errorCodes.Add(01114, "LSNRCTL could not perform local OS authentication with the listener");
            errorCodes.Add(01115, "OS error string creating shared memory segment of string bytes with key string");
            errorCodes.Add(01116, "Listener alias name given as connect identifier is too long");
            errorCodes.Add(01117, "Invalid argument was specified for stop command");
            errorCodes.Add(01150, "The address of the specified listener name is incorrect");
            errorCodes.Add(01151, "Missing listener name, string, in LISTENER.ORA");
            errorCodes.Add(01152, "All addresses specified for the listener name, string, failed");
            errorCodes.Add(01153, "Failed to process string:");
            errorCodes.Add(01154, "SID detected in old format that is no longer supported");
            errorCodes.Add(01155, "Incorrectly specified SID_LIST_string parameter in LISTENER.ORA");
            errorCodes.Add(01156, "Missing or inappropriate PROTOCOL, TIMEOUT or POOL_SIZE parameter from PRESPAWN_DESC");
            errorCodes.Add(01157, "Can only listen on number addresses - ignoring string");
            errorCodes.Add(01158, "Internal connection limit reached, preventing dispatcher from connecting");
            errorCodes.Add(01159, "Internal connection limit has been reached; listener has shut down");
            errorCodes.Add(01160, "Trace level was not specified");
            errorCodes.Add(01161, "Spawn alias string was not found. Check listener parameter file");
            errorCodes.Add(01162, "Syntax error in the address resolved from the spawn alias:");
            errorCodes.Add(01163, "Failed to spawn process:");
            errorCodes.Add(01164, "No spawn alias sent to listener");
            errorCodes.Add(01165, "Spawn alias has no program name set in it");
            errorCodes.Add(01167, "The command string is not supported by the listener contacted");
            errorCodes.Add(01168, "Cannot allocate memory");
            errorCodes.Add(01169, "The listener has not recognized the password");
            errorCodes.Add(01170, "Event detection broke for address:");
            errorCodes.Add(01171, "Event detection broke for dispatcher:");
            errorCodes.Add(01172, "Listener has shut down since all listen addresses have been deallocated");
            errorCodes.Add(01173, "Missing or inappropriate PRESPAWN_MAX parameter from SID_DESC");
            errorCodes.Add(01174, "The sum of the POOL_SIZEs from each PRESPAWN_DESC is greater than the PRESPAWN_MAX");
            errorCodes.Add(01175, "Password unchanged");
            errorCodes.Add(01176, "Error in loading the new parameter value");
            errorCodes.Add(01177, "Log Status is OFF. Log file/directory unchanged");
            errorCodes.Add(01178, "Trace Level is 0. Trace file/directory unchanged");
            errorCodes.Add(01180, "Missing listener object string in Directory Server");
            errorCodes.Add(01181, "Internal registration connection limit reached");
            errorCodes.Add(01182, "Listener rejected registration of service");
            errorCodes.Add(01183, "Listener rejected registration or update of instance");
            errorCodes.Add(01184, "Listener rejected registration or update of service handler");
            errorCodes.Add(01185, "Registration attempted from a remote node");
            errorCodes.Add(01186, "Client connection was dropped based on a filtering rule");
            errorCodes.Add(01187, "No proxy service handler available");
            errorCodes.Add(01188, "Listener cannot operate with incompatible transport protocols");
            errorCodes.Add(01189, "The listener could not authenticate the user");
            errorCodes.Add(01190, "The user is not authorized to execute the requested listener command");
            errorCodes.Add(01191, "Failed to initialize the local OS authentication subsystem");
            errorCodes.Add(01192, "Missing SID_LIST_ value left of equation for SID description in LISTENER.ORA");
            errorCodes.Add(01193, "Listener cannot operate with specified secure transport");
            errorCodes.Add(01194, "The listener command did not arrive in a secure transport");
            errorCodes.Add(01196, "Unable to initialize GSM IPC channel");
            errorCodes.Add(01197, "Listener failed to create the end point");
            errorCodes.Add(01198, "Listener failed to initialize valid node list");
            errorCodes.Add(01199, "Warning! Different databases have registered the same service");
            errorCodes.Add(01200, "The listener must be suid root");
            errorCodes.Add(01201, "Listener cannot find executable string for SID string");
            errorCodes.Add(01202, "Missing the dba group (string) specified by DBA_GROUP in SID_DESC");
            errorCodes.Add(01203, "Missing the account (string) specified by DEFAULT_USER_ACCOUNT in SID_DESC");
            errorCodes.Add(01204, "Unprivileged account (string) is in dba group (string)");
            errorCodes.Add(01250, "Failed to get ADR Path for trace/alert directory");
            errorCodes.Add(01251, "Cannot set trace/log directory under ADR");
            errorCodes.Add(01300, "ERROR at string");
            errorCodes.Add(01301, "TNS error structure:");
            errorCodes.Add(01302, "nr err code: number");
            errorCodes.Add(01303, "ns main err code: number");
            errorCodes.Add(01304, "ns secondary err code: number");
            errorCodes.Add(01305, "nt main err code: number");
            errorCodes.Add(01306, "nt secondary err code: number");
            errorCodes.Add(01307, "nt OS err code: number");
            errorCodes.Add(01401, "Class:");
            errorCodes.Add(01402, "TYPE:");
            errorCodes.Add(01403, "Load:");
            errorCodes.Add(01404, "Max Load:");
            errorCodes.Add(01405, "Host:");
            errorCodes.Add(01406, "ID:");
            errorCodes.Add(01407, "Status: string Total handlers: string Relevant handlers:");
            errorCodes.Add(01412, "Handler(s):");
            errorCodes.Add(01415, "Listening Endpoints Summary...");
            errorCodes.Add(01416, "Process ID string");
            errorCodes.Add(01420, "Presentation:");
            errorCodes.Add(01421, "Session:");
            errorCodes.Add(01422, "Default Service string");
            errorCodes.Add(01441, "Number of filtering rules currently in effect: number");
            errorCodes.Add(01442, "No filtering rules currently in effect.");
            errorCodes.Add(02020, "set displaymode RAW | COMPAT | NORMAL | VERBOSE: output mode for lsnrctl display");
            errorCodes.Add(02021, "DIRECT_HANDOFF can be either ON or OFF.");
            errorCodes.Add(02022, "show rules: Show rules that are currently in effect");
            errorCodes.Add(02401, "gbname string too long, allowed number characters");
            errorCodes.Add(02402, "Bad CLBGNAMES parameter in tnsnames.ora");
            errorCodes.Add(02403, "Bad alias string or alias not present in tnsnames.ora");
            errorCodes.Add(02404, "Service string contains no local handlers");
            errorCodes.Add(02405, "GMS call failed, check GMS logs.");
            errorCodes.Add(02501, "Authentication: no more roles");
            errorCodes.Add(02502, "Authentication: unable to find initialization function");
            errorCodes.Add(02503, "Parameter retrieval failed");
            errorCodes.Add(02504, "Parameter count retrieval failed");
            errorCodes.Add(02505, "Authentication: null context pointer provided");
            errorCodes.Add(02506, "Authentication: no type string");
            errorCodes.Add(02507, "Encryption: algorithm not installed");
            errorCodes.Add(02508, "Encryption: server negotiation response in error");
            errorCodes.Add(02509, "Authentication: invalid process state");
            errorCodes.Add(02510, "Invalid numeric data type");
            errorCodes.Add(02511, "Invalid data type");
            errorCodes.Add(02512, "Invalid status received");
            errorCodes.Add(02513, "Requested data type does not match retrieved type");
            errorCodes.Add(02514, "Invalid packet received");
            errorCodes.Add(02515, "Encryption/crypto-checksumming: unknown control type");
            errorCodes.Add(02516, "No data available");
            errorCodes.Add(02517, "key smaller than requested size");
            errorCodes.Add(02518, "key negotiation error");
            errorCodes.Add(02519, "no appropriate key-negotiation parameters");
            errorCodes.Add(02520, "encryption/crypto-checksumming: no Diffie-Hellman seed");
            errorCodes.Add(02521, "encryption/crypto-checksumming: Diffie-Hellman seed too small");
            errorCodes.Add(02524, "Authentication: privilege check failed");
            errorCodes.Add(02525, "encryption/crypto-checksumming: self test failed");
            errorCodes.Add(02526, "server proxy type does not match client type");
            errorCodes.Add(03501, "OK");
            errorCodes.Add(03502, "Insufficient arguments. Usage: tnsping address [count]");
            errorCodes.Add(03503, "Could not initialize NL");
            errorCodes.Add(03504, "Service name too long");
            errorCodes.Add(03505, "Failed to resolve name");
            errorCodes.Add(03506, "Failed to create address binding");
            errorCodes.Add(03507, "Failure looking for ADDRESS keyword");
            errorCodes.Add(03508, "Failed to create address string");
            errorCodes.Add(03509, "OK (number msec)");
            errorCodes.Add(03510, "Failed due to I/O error");
            errorCodes.Add(03511, "Used parameter files:string");
            errorCodes.Add(03512, "Used string adapter to resolve the alias");
            errorCodes.Add(03513, "Attempting to contact string");
            errorCodes.Add(03601, "Failed in route information collection");
            errorCodes.Add(03602, "Insufficient arguments. Usage: trcroute address");
            errorCodes.Add(03603, "Encountered a node with a version eariler than SQL*Net 2.3");
            errorCodes.Add(04001, "string");
            errorCodes.Add(04002, "The command completed successfully.");
            errorCodes.Add(04003, "Syntax Error.");
            errorCodes.Add(04004, "Unable to encrypt the supplied password.");
            errorCodes.Add(04005, "Unable to resolve address for string.");
            errorCodes.Add(04006, "Invalid password");
            errorCodes.Add(04007, "Internal error number.");
            errorCodes.Add(04008, "string | string");
            errorCodes.Add(04009, "string | number");
            errorCodes.Add(04010, "Command cannot be issued before the ADMINISTER command.");
            errorCodes.Add(04011, "Oracle Connection Manager instance not yet started.");
            errorCodes.Add(04012, "Unable to start Oracle Connection Manager instance.");
            errorCodes.Add(04013, "CMCTL timed out waiting for Oracle Connection Manager to start");
            errorCodes.Add(04014, "Current instance string is already started");
            errorCodes.Add(04015, "Current instance string is not yet started");
            errorCodes.Add(04016, "Connecting to string");
            errorCodes.Add(04017, "Please wait. Shutdown in progress.");
            errorCodes.Add(04018, "Instance already started");
            errorCodes.Add(04019, "Starting Oracle Connection Manager instance string. Please wait...");
            errorCodes.Add(04020, "CMCTL Version: number.number.number.number.number");
            errorCodes.Add(04021, "The SET command is unsuccessful for parameter string.");
            errorCodes.Add(04022, "string parameter string set to string.");
            errorCodes.Add(04023, "Command failed.");
            errorCodes.Add(04037, "Connections refer to string.");
            errorCodes.Add(04044, "Specified gateways do not exist.");
            errorCodes.Add(04045, "Invalid specification of time");
            errorCodes.Add(04046, "Invalid specification for source");
            errorCodes.Add(04047, "Invalid specification for destination");
            errorCodes.Add(04048, "Specified service does not exist.");
            errorCodes.Add(04049, "Specified connections do not exist");
            errorCodes.Add(04050, "Invalid specification for gateway ID.");
            errorCodes.Add(04063, "Remote administration disabled in the Oracle Connection Manager instance.");
            errorCodes.Add(04064, "The number of CMCTL sessions exceeds MAX_CMCTL_SESSIONS.");
            errorCodes.Add(04065, "The number of remote CMCTL sessions exceeds (MAX_CMCTL_SESSIONS-1)");
            errorCodes.Add(04066, "The following log events can be enabled or disabled:");
            errorCodes.Add(04067, "Number of connections: number.");
            errorCodes.Add(04068, "Cannot start an Oracle Connection Manager instance remotely.");
            errorCodes.Add(04069, "Sleeping for number seconds...");
            errorCodes.Add(04070, "Cannot administer a remote Oracle Connection Manager instance which is not yet started.");
            errorCodes.Add(04071, "Connections closed successfully. Number closed: number.");
            errorCodes.Add(04072, "Unable to suspend atleast one of the gateways.");
            errorCodes.Add(04073, "Passwords do not match.");
            errorCodes.Add(04074, "Invalid value for the parameter string.");
            errorCodes.Add(04075, "Cannot use ADMINISTER directly from the command line.");
            errorCodes.Add(04076, "Invalid specification for state.");
            errorCodes.Add(04077, "WARNING: No password set for the Oracle Connection Manager instance.");
            errorCodes.Add(04078, "Unable to resume atleast one of the gateways.");
            errorCodes.Add(04079, "Cannot administer Oracle Connection Manager with no CMAN.ORA, and port = number.");
            errorCodes.Add(04080, "Failed to reload");
            errorCodes.Add(04081, "Event groups:");
            errorCodes.Add(04082, "string event string set to string.");
            errorCodes.Add(04083, "Failed to save password");
            errorCodes.Add(04084, "WARNING: Non-reloadable parameters have retained their values.");
            errorCodes.Add(04085, "Password not changed since last save.");
            errorCodes.Add(04086, "Invalid value for the event string.");
            errorCodes.Add(04087, "Unable to shutdown atleast one of the gateways.");
            errorCodes.Add(04088, "Unable to close atleast one of the connections.");
            errorCodes.Add(04089, "Alias name too long.");
            errorCodes.Add(04140, "Migration completed successfully.");
            errorCodes.Add(04141, "Unable to find CMAN.ORA file.");
            errorCodes.Add(04142, "CMAN.ORA file has an invalid format.");
            errorCodes.Add(04143, "Unable to write the new CMAN.ORA file.");
            errorCodes.Add(04144, "Nothing to migrate");
            errorCodes.Add(04201, "Trace Assistant Usage ERROR: Missing File name");
            errorCodes.Add(04202, "Trace Assistant Usage ERROR: Not enough arguments ");
            errorCodes.Add(04203, "Trace Assistant Usage ERROR: Invalid options ");
            errorCodes.Add(04204, "Trace Assistant Internal ERROR: Couldn't Open trace file");
            errorCodes.Add(04205, "Trace Assistant Internal ERROR: Memory");
            errorCodes.Add(04206, "Trace Assistant Internal ERROR: Packet Type");
            errorCodes.Add(04207, "Trace Assistant Internal ERROR: Packet Length");
            errorCodes.Add(04208, "Trace Assistant Internal ERROR: Fatal");
            errorCodes.Add(04209, "Trace Assistant Internal ERROR: Type Error ");
            errorCodes.Add(04210, "Trace Assistant Internal ERROR: End of File");
            errorCodes.Add(04211, "Trace Assistant Internal ERROR: CORE");
            errorCodes.Add(04212, "Trace Assistant Internal ERROR: NACOM Type Error ");
            errorCodes.Add(04231, "Trace Assistant WARNING: Assuming Oracle trace format");
            errorCodes.Add(04232, "Trace Assistant WARNING: Not retrieving all rows ");
            errorCodes.Add(04233, "Trace Assistant WARNING: Going beyond Packet length");
            errorCodes.Add(04234, "Trace Assistant WARNING: won't decode TTC ");
            errorCodes.Add(04235, "Trace Assistant WARNING: Unknown TTC protocol");
            errorCodes.Add(12150, "TNS:unable to send data");
            errorCodes.Add(12151, "TNS:received bad packet type from network layer");
            errorCodes.Add(12152, "TNS:unable to send break message");
            errorCodes.Add(12153, "TNS:not connected");
            errorCodes.Add(12154, "TNS:could not resolve the connect identifier specified");
            errorCodes.Add(12155, "TNS:received bad datatype in NSWMARKER packet");
            errorCodes.Add(12156, "TNS:tried to reset line from incorrect state");
            errorCodes.Add(12157, "TNS:internal network communication error");
            errorCodes.Add(12158, "TNS:could not initialize parameter subsystem");
            errorCodes.Add(12159, "TNS:trace file not writeable");
            errorCodes.Add(12160, "TNS:internal error: Bad error number");
            errorCodes.Add(12161, "TNS:internal error: partial data received");
            errorCodes.Add(12162, "TNS:net service name is incorrectly specified");
            errorCodes.Add(12163, "TNS:connect descriptor is too long");
            errorCodes.Add(12164, "TNS:Sqlnet.fdf file not present");
            errorCodes.Add(12165, "TNS:Trying to write trace file into swap space.");
            errorCodes.Add(12166, "TNS:Client can not connect to HO agent.");
            errorCodes.Add(12168, "TNS:Unable to contact LDAP Directory Server");
            errorCodes.Add(12169, "TNS:Net service name given as connect identifier is too long");
            errorCodes.Add(12170, "TNS:Connect timeout occurred");
            errorCodes.Add(12171, "TNS:could not resolve connect identifier:");
            errorCodes.Add(12196, "TNS:received an error from TNS");
            errorCodes.Add(12197, "TNS:keyword-value resolution error");
            errorCodes.Add(12198, "TNS:could not find path to destination");
            errorCodes.Add(12200, "TNS:could not allocate memory");
            errorCodes.Add(12201, "TNS:encountered too small a connection buffer");
            errorCodes.Add(12202, "TNS:internal navigation error");
            errorCodes.Add(12203, "TNS:unable to connect to destination");
            errorCodes.Add(12204, "TNS:received data refused from an application");
            errorCodes.Add(12205, "TNS:could not get failed addresses");
            errorCodes.Add(12206, "TNS:received a TNS error during navigation");
            errorCodes.Add(12207, "TNS:unable to perform navigation");
            errorCodes.Add(12208, "TNS:could not find the TNSNAV.ORA file");
            errorCodes.Add(12209, "TNS:encountered uninitialized global");
            errorCodes.Add(12210, "TNS:error in finding Navigator data");
            errorCodes.Add(12211, "TNS:needs PREFERRED_CMANAGERS entry in TNSNAV.ORA");
            errorCodes.Add(12212, "TNS:incomplete PREFERRED_CMANAGERS binding in TNSNAV.ORA");
            errorCodes.Add(12213, "TNS:incomplete PREFERRED_CMANAGERS binding in TNSNAV.ORA");
            errorCodes.Add(12214, "TNS:missing local communities entry in TNSNAV.ORA");
            errorCodes.Add(12215, "TNS:poorly formed PREFERRED_NAVIGATORS Addresses in TNSNAV.ORA");
            errorCodes.Add(12216, "TNS:poorly formed PREFERRED_CMANAGERS addresses in TNSNAV.ORA");
            errorCodes.Add(12217, "TNS:could not contact PREFERRED_CMANAGERS in TNSNAV.ORA");
            errorCodes.Add(12218, "TNS:unacceptable network configuration data");
            errorCodes.Add(12219, "TNS:missing community name from address in ADDRESS_LIST");
            errorCodes.Add(12221, "TNS:illegal ADDRESS parameters");
            errorCodes.Add(12222, "TNS:no support is available for the protocol indicated");
            errorCodes.Add(12223, "TNS:internal limit restriction exceeded");
            errorCodes.Add(12224, "TNS:no listener");
            errorCodes.Add(12225, "TNS:destination host unreachable");
            errorCodes.Add(12226, "TNS:operating system resource quota exceeded");
            errorCodes.Add(12227, "TNS:syntax error");
            errorCodes.Add(12228, "TNS:protocol adapter not loadable");
            errorCodes.Add(12229, "TNS:Interchange has no more free connections");
            errorCodes.Add(12230, "TNS:Severe Network error occurred in making this connection");
            errorCodes.Add(12231, "TNS:No connection possible to destination");
            errorCodes.Add(12232, "TNS:No path available to destination");
            errorCodes.Add(12233, "TNS:Failure to accept a connection");
            errorCodes.Add(12234, "TNS:Redirect to destination");
            errorCodes.Add(12235, "TNS:Failure to redirect to destination");
            errorCodes.Add(12236, "TNS:protocol support not loaded");
            errorCodes.Add(12500, "TNS:listener failed to start a dedicated server process");
            errorCodes.Add(12502, "TNS:listener received no CONNECT_DATA from client");
            errorCodes.Add(12503, "TNS:listener received an invalid REGION from client");
            errorCodes.Add(12504, "TNS:listener was not given the SERVICE_NAME in CONNECT_DATA");
            errorCodes.Add(12505, "TNS:listener does not currently know of SID given in connect descriptor");
            errorCodes.Add(12508, "TNS:listener could not resolve the COMMAND given");
            errorCodes.Add(12509, "TNS:listener failed to redirect client to service handler");
            errorCodes.Add(12510, "TNS:database temporarily lacks resources to handle the request");
            errorCodes.Add(12511, "TNS:service handler found but it is not accepting connections");
            errorCodes.Add(12513, "TNS:service handler found but it has registered for a different protocol");
            errorCodes.Add(12514, "TNS:listener does not currently know of service requested in connect descriptor");
            errorCodes.Add(12515, "TNS:listener could not find a handler for this presentation");
            errorCodes.Add(12516, "TNS:listener could not find available handler with matching protocol stack");
            errorCodes.Add(12518, "TNS:listener could not hand off client connection");
            errorCodes.Add(12519, "TNS:no appropriate service handler found");
            errorCodes.Add(12520, "TNS:listener could not find available handler for requested type of server");
            errorCodes.Add(12521, "TNS:listener does not currently know of instance requested in connect descriptor");
            errorCodes.Add(12522, "TNS:listener could not find available instance with given INSTANCE_ROLE");
            errorCodes.Add(12523, "TNS:listener could not find instance appropriate for the client connection");
            errorCodes.Add(12524, "TNS:listener could not resolve HANDLER_NAME given in connect descriptor");
            errorCodes.Add(12525, "TNS:listener has not received client's request in time allowed");
            errorCodes.Add(12526, "TNS:listener: all appropriate instances are in restricted mode");
            errorCodes.Add(12527, "TNS:listener: all instances are in restricted mode or blocking new connections");
            errorCodes.Add(12528, "TNS:listener: all appropriate instances are blocking new connections");
            errorCodes.Add(12529, "TNS:connect request rejected based on current filtering rules");
            errorCodes.Add(12531, "TNS:cannot allocate memory");
            errorCodes.Add(12532, "TNS:invalid argument");
            errorCodes.Add(12533, "TNS:illegal ADDRESS parameters");
            errorCodes.Add(12534, "TNS:operation not supported");
            errorCodes.Add(12535, "TNS:operation timed out");
            errorCodes.Add(12536, "TNS:operation would block");
            errorCodes.Add(12537, "TNS:connection closed");
            errorCodes.Add(12538, "TNS:no such protocol adapter");
            errorCodes.Add(12539, "TNS:buffer over- or under-flow");
            errorCodes.Add(12540, "TNS:internal limit restriction exceeded");
            errorCodes.Add(12541, "TNS:no listener");
            errorCodes.Add(12542, "TNS:address already in use");
            errorCodes.Add(12543, "TNS:destination host unreachable");
            errorCodes.Add(12544, "TNS:contexts have different wait/test functions");
            errorCodes.Add(12545, "Connect failed because target host or object does not exist");
            errorCodes.Add(12546, "TNS:permission denied");
            errorCodes.Add(12547, "TNS:lost contact");
            errorCodes.Add(12548, "TNS:incomplete read or write");
            errorCodes.Add(12549, "TNS:operating system resource quota exceeded");
            errorCodes.Add(12550, "TNS:syntax error");
            errorCodes.Add(12551, "TNS:missing keyword");
            errorCodes.Add(12552, "TNS:operation was interrupted");
            errorCodes.Add(12554, "TNS:current operation is still in progress");
            errorCodes.Add(12555, "TNS:permission denied");
            errorCodes.Add(12556, "TNS:no caller");
            errorCodes.Add(12557, "TNS:protocol adapter not loadable");
            errorCodes.Add(12558, "TNS:protocol adapter not loaded");
            errorCodes.Add(12560, "TNS:protocol adapter error");
            errorCodes.Add(12561, "TNS:unknown error");
            errorCodes.Add(12562, "TNS:bad global handle");
            errorCodes.Add(12564, "TNS:connection refused");
            errorCodes.Add(12566, "TNS:protocol error");
            errorCodes.Add(12569, "TNS:packet checksum failure");
            errorCodes.Add(12570, "TNS:packet reader failure");
            errorCodes.Add(12571, "TNS:packet writer failure");
            errorCodes.Add(12574, "TNS:redirection denied");
            errorCodes.Add(12575, "TNS:dhctx busy");
            errorCodes.Add(12576, "TNS:handoff not supported for this session");
            errorCodes.Add(12578, "TNS:wallet open failed");
            errorCodes.Add(12582, "TNS:invalid operation");
            errorCodes.Add(12583, "TNS:no reader");
            errorCodes.Add(12585, "TNS:data truncation");
            errorCodes.Add(12589, "TNS:connection not bequeathable");
            errorCodes.Add(12590, "TNS:no I/O buffer");
            errorCodes.Add(12591, "TNS:event signal failure");
            errorCodes.Add(12592, "TNS:bad packet");
            errorCodes.Add(12593, "TNS:no registered connection");
            errorCodes.Add(12595, "TNS:no confirmation");
            errorCodes.Add(12596, "TNS:internal inconsistency");
            errorCodes.Add(12597, "TNS:connect descriptor already in use");
            errorCodes.Add(12598, "TNS:banner registration failed");
            errorCodes.Add(12599, "TNS:cryptographic checksum mismatch");
            errorCodes.Add(12600, "TNS: string open failed");
            errorCodes.Add(12601, "TNS:information flags check failed");
            errorCodes.Add(12602, "TNS: Connection Pooling limit reached");
            errorCodes.Add(12606, "TNS: Application timeout occurred");
            errorCodes.Add(12607, "TNS: Connect timeout occurred");
            errorCodes.Add(12608, "TNS: Send timeout occurred");
            errorCodes.Add(12609, "TNS: Receive timeout occurred");
            errorCodes.Add(12611, "TNS:operation is not portable");
            errorCodes.Add(12612, "TNS:connection is busy");
            errorCodes.Add(12615, "TNS:preempt error");
            errorCodes.Add(12616, "TNS:no event signals");
            errorCodes.Add(12618, "TNS:versions are incompatible");
            errorCodes.Add(12619, "TNS:unable to grant requested service");
            errorCodes.Add(12620, "TNS:requested characteristic not available");
            errorCodes.Add(12622, "TNS:event notifications are not homogeneous");
            errorCodes.Add(12623, "TNS:operation is illegal in this state");
            errorCodes.Add(12624, "TNS:connection is already registered");
            errorCodes.Add(12625, "TNS:missing argument");
            errorCodes.Add(12626, "TNS:bad event type");
            errorCodes.Add(12628, "TNS:no event callbacks");
            errorCodes.Add(12629, "TNS:no event test");
            errorCodes.Add(12630, "Native service operation not supported");
            errorCodes.Add(12631, "Username retrieval failed");
            errorCodes.Add(12632, "Role fetch failed");
            errorCodes.Add(12633, "No shared authentication services");
            errorCodes.Add(12634, "Memory allocation failed");
            errorCodes.Add(12635, "No authentication adapters available");
            errorCodes.Add(12636, "Packet send failed");
            errorCodes.Add(12637, "Packet receive failed");
            errorCodes.Add(12638, "Credential retrieval failed");
            errorCodes.Add(12639, "Authentication service negotiation failed");
            errorCodes.Add(12640, "Authentication adapter initialization failed");
            errorCodes.Add(12641, "Authentication service failed to initialize");
            errorCodes.Add(12642, "No session key");
            errorCodes.Add(12643, "Client received internal error from server");
            errorCodes.Add(12645, "Parameter does not exist.");
            errorCodes.Add(12646, "Invalid value specified for boolean parameter");
            errorCodes.Add(12647, "Authentication required");
            errorCodes.Add(12648, "Encryption or data integrity algorithm list empty");
            errorCodes.Add(12649, "Unknown encryption or data integrity algorithm");
            errorCodes.Add(12650, "No common encryption or data integrity algorithm");
            errorCodes.Add(12651, "Encryption or data integrity algorithm unacceptable");
            errorCodes.Add(12652, "String truncated");
            errorCodes.Add(12653, "Authentication control function failed");
            errorCodes.Add(12654, "Authentication conversion failed");
            errorCodes.Add(12655, "Password check failed");
            errorCodes.Add(12656, "Cryptographic checksum mismatch");
            errorCodes.Add(12657, "No algorithms installed");
            errorCodes.Add(12658, "ANO service required but TNS version is incompatible");
            errorCodes.Add(12659, "Error received from other process");
            errorCodes.Add(12660, "Encryption or crypto-checksumming parameters incompatible");
            errorCodes.Add(12661, "Protocol authentication to be used");
            errorCodes.Add(12662, "proxy ticket retrieval failed");
            errorCodes.Add(12663, "Services required by client not available on the server");
            errorCodes.Add(12664, "Services required by server not available on the client");
            errorCodes.Add(12665, "NLS string open failed");
            errorCodes.Add(12666, "Dedicated server: outbound transport protocol different from inbound");
            errorCodes.Add(12667, "Shared server: outbound transport protocol different from inbound");
            errorCodes.Add(12668, "Dedicated server: outbound protocol does not support proxies");
            errorCodes.Add(12669, "Shared server: outbound protocol does not support proxies");
            errorCodes.Add(12670, "Incorrect role password");
            errorCodes.Add(12671, "Shared server: adapter failed to save context");
            errorCodes.Add(12672, "Database logon failure");
            errorCodes.Add(12673, "Dedicated server: context not saved");
            errorCodes.Add(12674, "Shared server: proxy context not saved");
            errorCodes.Add(12675, "External user name not available yet");
            errorCodes.Add(12676, "Server received internal error from client");
            errorCodes.Add(12677, "Authentication service not supported by database link");
            errorCodes.Add(12678, "Authentication disabled but required");
            errorCodes.Add(12679, "Native services disabled by other process but required");
            errorCodes.Add(12680, "Native services disabled but required");
            errorCodes.Add(12681, "Login failed: the SecurID card does not have a pincode yet");
            errorCodes.Add(12682, "Login failed: the SecurID card is in next PRN mode");
            errorCodes.Add(12683, "encryption/crypto-checksumming: no Diffie-Hellman seed");
            errorCodes.Add(12684, "encryption/crypto-checksumming: Diffie-Hellman seed too small");
            errorCodes.Add(12685, "Native service required remotely but disabled locally");
            errorCodes.Add(12686, "Invalid command specified for a service");
            errorCodes.Add(12687, "Credentials expired.");
            errorCodes.Add(12688, "Login failed: the SecurID server rejected the new pincode");
            errorCodes.Add(12689, "Server Authentication required, but not supported");
            errorCodes.Add(12690, "Server Authentication failed, login cancelled");
            errorCodes.Add(12696, "Double Encryption Turned On, login disallowed");
            errorCodes.Add(12699, "Native service internal error");
        }
    }
}